feat!: update config interface to accept full path
edgexfoundry/go-mod-configuration pull request #89
Opened 2023-02-24 23:26 UTC by ejlee3

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-configuration/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) - no tests for similar functions, integration tested instead
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) - docs need to be added for common config
  <link to docs PR>

## Testing Instructions

**Non-secure mode testing**
1. set the environment variable for non-secure testing `export EDGEX_SECURITY_SECRET_STORE=false`
2. run the latest compose builder `make run no-secty` to start core services
3. stop core data
4. remove the core data configuration in consul
5. modify local go-mod in edgex-go to use bootstrap from [this branch](https://github.com/ejlee3/go-mod-bootstrap/tree/update-config-ready) and config from [this branch](https://github.com/ejlee3/go-mod-bootstrap/tree/update-config-ready) using `replace` statement
7. build common config and core data `make data`
9. run core-data locally and ensure that the configuration loads `cd cmd/core-data` and `./core-data -cp`
10. Verify that the core data configuration was loaded into consul
11. Modify the writable log level and ensure the terminal reflects the change

**Secure mode testing**
1. set the environment variable for non-secure testing `export EDGEX_SECURITY_SECRET_STORE=true`
2. run the latest compose builder `make run` to start core services
3. stop core data
4. remove the core data configuration in consul
5. modify local go-mod in edgex-go to use bootstrap from [this branch](https://github.com/ejlee3/go-mod-bootstrap/tree/update-config-ready) and config from [this branch](https://github.com/ejlee3/go-mod-bootstrap/tree/update-config-ready) using `replace` statement
7. build common config and core data `make data`
9. run core-data locally and ensure that the configuration loads `cd cmd/core-data` and `sudo ./core-data -cp`
10. Verify that the core data configuration was loaded into consul
11. Modify the writable log level and ensure the terminal reflects the change

## New Dependency Instructions (If applicable)

2023-02-25 00:42 UTC, lenny-intel requested changes

2023-02-25 00:42 UTC, lenny-intel commented on internal/pkg/consul/client.go
> +func (client *consulClient) GetConfigurationValueByFullPath(name string) ([]byte, error) {
```suggestion
func (client *consulClient) GetConfigurationValueByFullPath(fullPath string) ([]byte, error) {
```

2023-02-27 17:06 UTC, ejlee3 commented on internal/pkg/consul/client.go
> +func (client *consulClient) GetConfigurationValueByFullPath(name string) ([]byte, error) {
done

2023-02-27 17:15 UTC, lenny-intel approved these changes
LGTM

2023-02-27 17:15 UTC, merged